version: '3'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
    networks:
      virce-network:
        ipv4_address:
          10.254.0.100
  
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
        - "./data/mysql:/var/lib/mysql"
        - "./MySQL:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: virce
      MYSQL_USER: virce
      MYSQL_PASSWORD: virce
    networks:
      virce-network:
        ipv4_address:
          10.254.0.200
  
  virce-server1:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000/udp"
    depends_on: 
      - redis
      - mysql
    environment:
      REDIS_HOST: 10.254.0.100
      MYSQL_HOST: 10.254.0.200
    networks:
      virce-network:
        ipv4_address:
          10.254.0.11
  
networks:
  virce-network:
    ipam:
      driver: default
      config:
        - subnet: 10.254.0.0/16