// <auto-generated />
#pragma warning disable CS0105
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using System.Collections.Generic;
using System;
using VIRCE_server.DataBase;

namespace VIRCE_server.MasterMemoryDataBase.Tables
{
   public sealed partial class RoomServerInfoTable : TableBase<RoomServerInfo>, ITableUniqueValidate
   {
        public Func<RoomServerInfo, byte> PrimaryKeySelector => primaryIndexSelector;
        readonly Func<RoomServerInfo, byte> primaryIndexSelector;


        public RoomServerInfoTable(RoomServerInfo[] sortedData)
            : base(sortedData)
        {
            this.primaryIndexSelector = x => x.RoomID;
            OnAfterConstruct();
        }

        partial void OnAfterConstruct();


        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public RoomServerInfo FindByRoomID(byte key)
        {
            var lo = 0;
            var hi = data.Length - 1;
            while (lo <= hi)
            {
                var mid = (int)(((uint)hi + (uint)lo) >> 1);
                var selected = data[mid].RoomID;
                var found = (selected < key) ? -1 : (selected > key) ? 1 : 0;
                if (found == 0) { return data[mid]; }
                if (found < 0) { lo = mid + 1; }
                else { hi = mid - 1; }
            }
            return default;
        }

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public bool TryFindByRoomID(byte key, out RoomServerInfo result)
        {
            var lo = 0;
            var hi = data.Length - 1;
            while (lo <= hi)
            {
                var mid = (int)(((uint)hi + (uint)lo) >> 1);
                var selected = data[mid].RoomID;
                var found = (selected < key) ? -1 : (selected > key) ? 1 : 0;
                if (found == 0) { result = data[mid]; return true; }
                if (found < 0) { lo = mid + 1; }
                else { hi = mid - 1; }
            }
            result = default;
            return false;
        }

        public RoomServerInfo FindClosestByRoomID(byte key, bool selectLower = true)
        {
            return FindUniqueClosestCore(data, primaryIndexSelector, System.Collections.Generic.Comparer<byte>.Default, key, selectLower);
        }

        public RangeView<RoomServerInfo> FindRangeByRoomID(byte min, byte max, bool ascendant = true)
        {
            return FindUniqueRangeCore(data, primaryIndexSelector, System.Collections.Generic.Comparer<byte>.Default, min, max, ascendant);
        }


        void ITableUniqueValidate.ValidateUnique(ValidateResult resultSet)
        {
#if !DISABLE_MASTERMEMORY_VALIDATOR

            ValidateUniqueCore(data, primaryIndexSelector, "RoomID", resultSet);       

#endif
        }

#if !DISABLE_MASTERMEMORY_METADATABASE

        public static MasterMemory.Meta.MetaTable CreateMetaTable()
        {
            return new MasterMemory.Meta.MetaTable(typeof(RoomServerInfo), typeof(RoomServerInfoTable), "RoomServerInfo",
                new MasterMemory.Meta.MetaProperty[]
                {
                    new MasterMemory.Meta.MetaProperty(typeof(RoomServerInfo).GetProperty("RoomID")),
                    new MasterMemory.Meta.MetaProperty(typeof(RoomServerInfo).GetProperty("RoomType")),
                },
                new MasterMemory.Meta.MetaIndex[]{
                    new MasterMemory.Meta.MetaIndex(new System.Reflection.PropertyInfo[] {
                        typeof(RoomServerInfo).GetProperty("RoomID"),
                    }, true, true, System.Collections.Generic.Comparer<byte>.Default),
                });
        }

#endif
    }
}