// <auto-generated />
#pragma warning disable CS0105
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using System.Collections.Generic;
using System.Net;
using System;
using VIRCE_server.DataBase;

namespace VIRCE_server.MasterMemoryDataBase.Tables
{
   public sealed partial class UserDataTable : TableBase<UserData>, ITableUniqueValidate
   {
        public Func<UserData, int> PrimaryKeySelector => primaryIndexSelector;
        readonly Func<UserData, int> primaryIndexSelector;

        readonly UserData[] secondaryIndex0;
        readonly Func<UserData, ushort> secondaryIndex0Selector;
        readonly UserData[] secondaryIndex1;
        readonly Func<UserData, int> secondaryIndex1Selector;

        public UserDataTable(UserData[] sortedData)
            : base(sortedData)
        {
            this.primaryIndexSelector = x => x.GlobalUserId;
            this.secondaryIndex0Selector = x => x.UserId;
            this.secondaryIndex0 = CloneAndSortBy(this.secondaryIndex0Selector, System.Collections.Generic.Comparer<ushort>.Default);
            this.secondaryIndex1Selector = x => x.RoomId;
            this.secondaryIndex1 = CloneAndSortBy(this.secondaryIndex1Selector, System.Collections.Generic.Comparer<int>.Default);
            OnAfterConstruct();
        }

        partial void OnAfterConstruct();

        public RangeView<UserData> SortByUserId => new RangeView<UserData>(secondaryIndex0, 0, secondaryIndex0.Length - 1, true);
        public RangeView<UserData> SortByRoomId => new RangeView<UserData>(secondaryIndex1, 0, secondaryIndex1.Length - 1, true);

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public UserData FindByGlobalUserId(int key)
        {
            var lo = 0;
            var hi = data.Length - 1;
            while (lo <= hi)
            {
                var mid = (int)(((uint)hi + (uint)lo) >> 1);
                var selected = data[mid].GlobalUserId;
                var found = (selected < key) ? -1 : (selected > key) ? 1 : 0;
                if (found == 0) { return data[mid]; }
                if (found < 0) { lo = mid + 1; }
                else { hi = mid - 1; }
            }
            return default;
        }

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public bool TryFindByGlobalUserId(int key, out UserData result)
        {
            var lo = 0;
            var hi = data.Length - 1;
            while (lo <= hi)
            {
                var mid = (int)(((uint)hi + (uint)lo) >> 1);
                var selected = data[mid].GlobalUserId;
                var found = (selected < key) ? -1 : (selected > key) ? 1 : 0;
                if (found == 0) { result = data[mid]; return true; }
                if (found < 0) { lo = mid + 1; }
                else { hi = mid - 1; }
            }
            result = default;
            return false;
        }

        public UserData FindClosestByGlobalUserId(int key, bool selectLower = true)
        {
            return FindUniqueClosestCore(data, primaryIndexSelector, System.Collections.Generic.Comparer<int>.Default, key, selectLower);
        }

        public RangeView<UserData> FindRangeByGlobalUserId(int min, int max, bool ascendant = true)
        {
            return FindUniqueRangeCore(data, primaryIndexSelector, System.Collections.Generic.Comparer<int>.Default, min, max, ascendant);
        }

        public RangeView<UserData> FindByUserId(ushort key)
        {
            return FindManyCore(secondaryIndex0, secondaryIndex0Selector, System.Collections.Generic.Comparer<ushort>.Default, key);
        }

        public RangeView<UserData> FindClosestByUserId(ushort key, bool selectLower = true)
        {
            return FindManyClosestCore(secondaryIndex0, secondaryIndex0Selector, System.Collections.Generic.Comparer<ushort>.Default, key, selectLower);
        }

        public RangeView<UserData> FindRangeByUserId(ushort min, ushort max, bool ascendant = true)
        {
            return FindManyRangeCore(secondaryIndex0, secondaryIndex0Selector, System.Collections.Generic.Comparer<ushort>.Default, min, max, ascendant);
        }

        public RangeView<UserData> FindByRoomId(int key)
        {
            return FindManyCore(secondaryIndex1, secondaryIndex1Selector, System.Collections.Generic.Comparer<int>.Default, key);
        }

        public RangeView<UserData> FindClosestByRoomId(int key, bool selectLower = true)
        {
            return FindManyClosestCore(secondaryIndex1, secondaryIndex1Selector, System.Collections.Generic.Comparer<int>.Default, key, selectLower);
        }

        public RangeView<UserData> FindRangeByRoomId(int min, int max, bool ascendant = true)
        {
            return FindManyRangeCore(secondaryIndex1, secondaryIndex1Selector, System.Collections.Generic.Comparer<int>.Default, min, max, ascendant);
        }


        void ITableUniqueValidate.ValidateUnique(ValidateResult resultSet)
        {
#if !DISABLE_MASTERMEMORY_VALIDATOR

            ValidateUniqueCore(data, primaryIndexSelector, "GlobalUserId", resultSet);       

#endif
        }

#if !DISABLE_MASTERMEMORY_METADATABASE

        public static MasterMemory.Meta.MetaTable CreateMetaTable()
        {
            return new MasterMemory.Meta.MetaTable(typeof(UserData), typeof(UserDataTable), "UserData",
                new MasterMemory.Meta.MetaProperty[]
                {
                    new MasterMemory.Meta.MetaProperty(typeof(UserData).GetProperty("GlobalUserId")),
                    new MasterMemory.Meta.MetaProperty(typeof(UserData).GetProperty("UserId")),
                    new MasterMemory.Meta.MetaProperty(typeof(UserData).GetProperty("RoomId")),
                    new MasterMemory.Meta.MetaProperty(typeof(UserData).GetProperty("ModelId")),
                    new MasterMemory.Meta.MetaProperty(typeof(UserData).GetProperty("Name")),
                    new MasterMemory.Meta.MetaProperty(typeof(UserData).GetProperty("RemoteEndPoint")),
                },
                new MasterMemory.Meta.MetaIndex[]{
                    new MasterMemory.Meta.MetaIndex(new System.Reflection.PropertyInfo[] {
                        typeof(UserData).GetProperty("GlobalUserId"),
                    }, true, true, System.Collections.Generic.Comparer<int>.Default),
                    new MasterMemory.Meta.MetaIndex(new System.Reflection.PropertyInfo[] {
                        typeof(UserData).GetProperty("UserId"),
                    }, false, false, System.Collections.Generic.Comparer<ushort>.Default),
                    new MasterMemory.Meta.MetaIndex(new System.Reflection.PropertyInfo[] {
                        typeof(UserData).GetProperty("RoomId"),
                    }, false, false, System.Collections.Generic.Comparer<int>.Default),
                });
        }

#endif
    }
}