// <auto-generated />
#pragma warning disable CS0105
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using System.Collections.Generic;
using System.Net;
using System;
using VIRCE_server.DataBase;
using VIRCE_server.Tables;

namespace VIRCE_server
{
   public sealed class ImmutableBuilder : ImmutableBuilderBase
   {
        MemoryDatabase memory;

        public ImmutableBuilder(MemoryDatabase memory)
        {
            this.memory = memory;
        }

        public MemoryDatabase Build()
        {
            return memory;
        }

        public void ReplaceAll(System.Collections.Generic.IList<UserData> data)
        {
            var newData = CloneAndSortBy(data, x => x.GlobalUserId, System.Collections.Generic.Comparer<int>.Default);
            var table = new UserDataTable(newData);
            memory = new MemoryDatabase(
                table
            
            );
        }

        public void RemoveUserData(int[] keys)
        {
            var data = RemoveCore(memory.UserDataTable.GetRawDataUnsafe(), keys, x => x.GlobalUserId, System.Collections.Generic.Comparer<int>.Default);
            var newData = CloneAndSortBy(data, x => x.GlobalUserId, System.Collections.Generic.Comparer<int>.Default);
            var table = new UserDataTable(newData);
            memory = new MemoryDatabase(
                table
            
            );
        }

        public void Diff(UserData[] addOrReplaceData)
        {
            var data = DiffCore(memory.UserDataTable.GetRawDataUnsafe(), addOrReplaceData, x => x.GlobalUserId, System.Collections.Generic.Comparer<int>.Default);
            var newData = CloneAndSortBy(data, x => x.GlobalUserId, System.Collections.Generic.Comparer<int>.Default);
            var table = new UserDataTable(newData);
            memory = new MemoryDatabase(
                table
            
            );
        }

    }
}