// <auto-generated />
#pragma warning disable CS0105
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using System.Collections.Generic;
using System.Net;
using System;
using VIRCE_server.DataBase;
using VIRCE_server.MasterMemoryDataBase.Tables;

namespace VIRCE_server.MasterMemoryDataBase
{
   public sealed class ImmutableBuilder : ImmutableBuilderBase
   {
        MemoryDatabase memory;

        public ImmutableBuilder(MemoryDatabase memory)
        {
            this.memory = memory;
        }

        public MemoryDatabase Build()
        {
            return memory;
        }

        public void ReplaceAll(System.Collections.Generic.IList<RoomServerInfo> data)
        {
            var newData = CloneAndSortBy(data, x => x.RoomId, System.Collections.Generic.Comparer<byte>.Default);
            var table = new RoomServerInfoTable(newData);
            memory = new MemoryDatabase(
                table,
                memory.UserDataTable
            
            );
        }

        public void RemoveRoomServerInfo(byte[] keys)
        {
            var data = RemoveCore(memory.RoomServerInfoTable.GetRawDataUnsafe(), keys, x => x.RoomId, System.Collections.Generic.Comparer<byte>.Default);
            var newData = CloneAndSortBy(data, x => x.RoomId, System.Collections.Generic.Comparer<byte>.Default);
            var table = new RoomServerInfoTable(newData);
            memory = new MemoryDatabase(
                table,
                memory.UserDataTable
            
            );
        }

        public void Diff(RoomServerInfo[] addOrReplaceData)
        {
            var data = DiffCore(memory.RoomServerInfoTable.GetRawDataUnsafe(), addOrReplaceData, x => x.RoomId, System.Collections.Generic.Comparer<byte>.Default);
            var newData = CloneAndSortBy(data, x => x.RoomId, System.Collections.Generic.Comparer<byte>.Default);
            var table = new RoomServerInfoTable(newData);
            memory = new MemoryDatabase(
                table,
                memory.UserDataTable
            
            );
        }

        public void ReplaceAll(System.Collections.Generic.IList<UserData> data)
        {
            var newData = CloneAndSortBy(data, x => x.GlobalUserId, System.Collections.Generic.Comparer<ushort>.Default);
            var table = new UserDataTable(newData);
            memory = new MemoryDatabase(
                memory.RoomServerInfoTable,
                table
            
            );
        }

        public void RemoveUserData(ushort[] keys)
        {
            var data = RemoveCore(memory.UserDataTable.GetRawDataUnsafe(), keys, x => x.GlobalUserId, System.Collections.Generic.Comparer<ushort>.Default);
            var newData = CloneAndSortBy(data, x => x.GlobalUserId, System.Collections.Generic.Comparer<ushort>.Default);
            var table = new UserDataTable(newData);
            memory = new MemoryDatabase(
                memory.RoomServerInfoTable,
                table
            
            );
        }

        public void Diff(UserData[] addOrReplaceData)
        {
            var data = DiffCore(memory.UserDataTable.GetRawDataUnsafe(), addOrReplaceData, x => x.GlobalUserId, System.Collections.Generic.Comparer<ushort>.Default);
            var newData = CloneAndSortBy(data, x => x.GlobalUserId, System.Collections.Generic.Comparer<ushort>.Default);
            var table = new UserDataTable(newData);
            memory = new MemoryDatabase(
                memory.RoomServerInfoTable,
                table
            
            );
        }

    }
}