// <auto-generated />
#pragma warning disable CS0105
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using System.Collections.Generic;
using System.Net;
using System;
using VIRCE_server.DataBase;
using VIRCE_server.MasterMemoryDataBase.Tables;

namespace VIRCE_server.MasterMemoryDataBase
{
   public sealed class MemoryDatabase : MemoryDatabaseBase
   {
        public RoomServerInfoTable RoomServerInfoTable { get; private set; }
        public UserDataTable UserDataTable { get; private set; }

        public MemoryDatabase(
            RoomServerInfoTable RoomServerInfoTable,
            UserDataTable UserDataTable
        )
        {
            this.RoomServerInfoTable = RoomServerInfoTable;
            this.UserDataTable = UserDataTable;
        }

        public MemoryDatabase(byte[] databaseBinary, bool internString = true, MessagePack.IFormatterResolver formatterResolver = null, int maxDegreeOfParallelism = 1)
            : base(databaseBinary, internString, formatterResolver, maxDegreeOfParallelism)
        {
        }

        protected override void Init(Dictionary<string, (int offset, int count)> header, System.ReadOnlyMemory<byte> databaseBinary, MessagePack.MessagePackSerializerOptions options, int maxDegreeOfParallelism)
        {
            if(maxDegreeOfParallelism == 1)
            {
                InitSequential(header, databaseBinary, options, maxDegreeOfParallelism);
            }
            else
            {
                InitParallel(header, databaseBinary, options, maxDegreeOfParallelism);
            }
        }

        void InitSequential(Dictionary<string, (int offset, int count)> header, System.ReadOnlyMemory<byte> databaseBinary, MessagePack.MessagePackSerializerOptions options, int maxDegreeOfParallelism)
        {
            this.RoomServerInfoTable = ExtractTableData<RoomServerInfo, RoomServerInfoTable>(header, databaseBinary, options, xs => new RoomServerInfoTable(xs));
            this.UserDataTable = ExtractTableData<UserData, UserDataTable>(header, databaseBinary, options, xs => new UserDataTable(xs));
        }

        void InitParallel(Dictionary<string, (int offset, int count)> header, System.ReadOnlyMemory<byte> databaseBinary, MessagePack.MessagePackSerializerOptions options, int maxDegreeOfParallelism)
        {
            var extracts = new Action[]
            {
                () => this.RoomServerInfoTable = ExtractTableData<RoomServerInfo, RoomServerInfoTable>(header, databaseBinary, options, xs => new RoomServerInfoTable(xs)),
                () => this.UserDataTable = ExtractTableData<UserData, UserDataTable>(header, databaseBinary, options, xs => new UserDataTable(xs)),
            };
            
            System.Threading.Tasks.Parallel.Invoke(new System.Threading.Tasks.ParallelOptions
            {
                MaxDegreeOfParallelism = maxDegreeOfParallelism
            }, extracts);
        }

        public ImmutableBuilder ToImmutableBuilder()
        {
            return new ImmutableBuilder(this);
        }

        public DatabaseBuilder ToDatabaseBuilder()
        {
            var builder = new DatabaseBuilder();
            builder.Append(this.RoomServerInfoTable.GetRawDataUnsafe());
            builder.Append(this.UserDataTable.GetRawDataUnsafe());
            return builder;
        }

        public DatabaseBuilder ToDatabaseBuilder(MessagePack.IFormatterResolver resolver)
        {
            var builder = new DatabaseBuilder(resolver);
            builder.Append(this.RoomServerInfoTable.GetRawDataUnsafe());
            builder.Append(this.UserDataTable.GetRawDataUnsafe());
            return builder;
        }

#if !DISABLE_MASTERMEMORY_VALIDATOR

        public ValidateResult Validate()
        {
            var result = new ValidateResult();
            var database = new ValidationDatabase(new object[]
            {
                RoomServerInfoTable,
                UserDataTable,
            });

            ((ITableUniqueValidate)RoomServerInfoTable).ValidateUnique(result);
            ValidateTable(RoomServerInfoTable.All, database, "RoomId", RoomServerInfoTable.PrimaryKeySelector, result);
            ((ITableUniqueValidate)UserDataTable).ValidateUnique(result);
            ValidateTable(UserDataTable.All, database, "GlobalUserId", UserDataTable.PrimaryKeySelector, result);

            return result;
        }

#endif

        static MasterMemory.Meta.MetaDatabase metaTable;

        public static object GetTable(MemoryDatabase db, string tableName)
        {
            switch (tableName)
            {
                case "RoomServerInfo":
                    return db.RoomServerInfoTable;
                case "UserData":
                    return db.UserDataTable;
                
                default:
                    return null;
            }
        }

#if !DISABLE_MASTERMEMORY_METADATABASE

        public static MasterMemory.Meta.MetaDatabase GetMetaDatabase()
        {
            if (metaTable != null) return metaTable;

            var dict = new Dictionary<string, MasterMemory.Meta.MetaTable>();
            dict.Add("RoomServerInfo", VIRCE_server.MasterMemoryDataBase.Tables.RoomServerInfoTable.CreateMetaTable());
            dict.Add("UserData", VIRCE_server.MasterMemoryDataBase.Tables.UserDataTable.CreateMetaTable());

            metaTable = new MasterMemory.Meta.MetaDatabase(dict);
            return metaTable;
        }

#endif
    }
}