---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "virce-server"
  namespace: "default"
  labels:
    app: "virce-server"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "virce-server"
  template:
    metadata:
      labels:
        app: "virce-server"
    spec:
      containers:
        - name: "server-1"
          image: "gcr.io/virce-401702/github.com/gto-gamblerteacheroka/server:$SHORT_SHA"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "virce-server-hpa-blof"
  namespace: "default"
  labels:
    app: "virce-server"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "virce-server"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: "Utilization"
          averageUtilization: 80
